# ==============================================
# KESSEL-WEB : Correction orthographique (accents)
# Exécuter depuis C:\Users\user\Desktop\kessel-web\
# ==============================================

$projectPath = "C:\Users\user\Desktop\kessel-web"

# Liste des remplacements (sans accent -> avec accent)
$replacements = @{
    # Mots courants
    "a propos" = "à propos"
    "A propos" = "À propos"
    "deja" = "déjà"
    "Deja" = "Déjà"
    "voila" = "voilà"
    "Voila" = "Voilà"
    "ou " = "où "
    "Ou " = "Où "
    "la " = "là "  # Attention: contextuel, on le fera manuellement
    "ca " = "ça "
    "Ca " = "Ça "
    
    # Verbes être
    "etes" = "êtes"
    "Etes" = "Êtes"
    "etre" = "être"
    "Etre" = "Être"
    
    # Accents aigus (é)
    "etape" = "étape"
    "Etape" = "Étape"
    "equipe" = "équipe"
    "Equipe" = "Équipe"
    "ecran" = "écran"
    "Ecran" = "Écran"
    "economie" = "économie"
    "Economie" = "Économie"
    "economique" = "économique"
    "Economique" = "Économique"
    "energie" = "énergie"
    "Energie" = "Énergie"
    "evenement" = "événement"
    "Evenement" = "Événement"
    "etat" = "état"
    "Etat" = "État"
    "etude" = "étude"
    "Etude" = "Étude"
    "elevage" = "élevage"
    "Elevage" = "Élevage"
    "eleveur" = "éleveur"
    "Eleveur" = "Éleveur"
    "recolte" = "récolte"
    "Recolte" = "Récolte"
    "cereale" = "céréale"
    "Cereale" = "Céréale"
    "cereales" = "céréales"
    "Cereales" = "Céréales"
    "legume" = "légume"
    "Legume" = "Légume"
    "legumes" = "légumes"
    "Legumes" = "Légumes"
    "legumineuse" = "légumineuse"
    "Legumineuse" = "Légumineuse"
    "securite" = "sécurité"
    "Securite" = "Sécurité"
    "generale" = "générale"
    "Generale" = "Générale"
    "generales" = "générales"
    "Generales" = "Générales"
    "genere" = "génère"
    "Genere" = "Génère"
    "regenere" = "régénère"
    "methode" = "méthode"
    "Methode" = "Méthode"
    "periode" = "période"
    "Periode" = "Période"
    "telecharger" = "télécharger"
    "Telecharger" = "Télécharger"
    "telechargez" = "téléchargez"
    "Telechargez" = "Téléchargez"
    "telephone" = "téléphone"
    "Telephone" = "Téléphone"
    "televise" = "télévisé"
    "presente" = "présente"
    "Presente" = "Présente"
    "presentee" = "présentée"
    "preference" = "préférence"
    "Preference" = "Préférence"
    "different" = "différent"
    "Different" = "Différent"
    "differente" = "différente"
    "differents" = "différents"
    "interessant" = "intéressant"
    "Interessant" = "Intéressant"
    "interesse" = "intéressé"
    "necessaire" = "nécessaire"
    "Necessaire" = "Nécessaire"
    "necessaires" = "nécessaires"
    "developpement" = "développement"
    "Developpement" = "Développement"
    "developpe" = "développe"
    "Developpe" = "Développe"
    "repondre" = "répondre"
    "Repondre" = "Répondre"
    "repond" = "répond"
    "reponse" = "réponse"
    "Reponse" = "Réponse"
    "reseau" = "réseau"
    "Reseau" = "Réseau"
    "resume" = "résumé"
    "Resume" = "Résumé"
    "resultat" = "résultat"
    "Resultat" = "Résultat"
    "resultats" = "résultats"
    "Resultats" = "Résultats"
    "reference" = "référence"
    "Reference" = "Référence"
    "references" = "références"
    "region" = "région"
    "Region" = "Région"
    "regions" = "régions"
    "Regions" = "Régions"
    "regulier" = "régulier"
    "Regulier" = "Régulier"
    "reguliere" = "régulière"
    "repartition" = "répartition"
    "Repartition" = "Répartition"
    "repertoire" = "répertoire"
    "rendement" = "rendement"  # Celui-ci est correct
    "benefice" = "bénéfice"
    "Benefice" = "Bénéfice"
    "benefices" = "bénéfices"
    "beneficiaire" = "bénéficiaire"
    "Beneficiaire" = "Bénéficiaire"
    "beneficiaires" = "bénéficiaires"
    "specifique" = "spécifique"
    "Specifique" = "Spécifique"
    "specifiques" = "spécifiques"
    "specificite" = "spécificité"
    "specialise" = "spécialisé"
    "specialisee" = "spécialisée"
    "speculation" = "spéculation"
    "Speculation" = "Spéculation"
    "speculations" = "spéculations"
    "Speculations" = "Spéculations"
    "prevision" = "prévision"
    "Prevision" = "Prévision"
    "previsions" = "prévisions"
    "prevu" = "prévu"
    "prevue" = "prévue"
    "prevoir" = "prévoir"
    "precis" = "précis"
    "Precis" = "Précis"
    "precise" = "précise"
    "precision" = "précision"
    "preparation" = "préparation"
    "Preparation" = "Préparation"
    "preparer" = "préparer"
    "prepare" = "prépare"
    "premiere" = "première"
    "Premiere" = "Première"
    "premieres" = "premières"
    "prefere" = "préfère"
    "Prefere" = "Préfère"
    "recommande" = "recommandé"
    "Recommande" = "Recommandé"
    "recommandee" = "recommandée"
    "demarrer" = "démarrer"
    "Demarrer" = "Démarrer"
    "demarre" = "démarre"
    "demarrage" = "démarrage"
    "debuter" = "débuter"
    "Debuter" = "Débuter"
    "debut" = "début"
    "Debut" = "Début"
    "decembre" = "décembre"
    "Decembre" = "Décembre"
    "decision" = "décision"
    "Decision" = "Décision"
    "declarer" = "déclarer"
    "declare" = "déclaré"
    "decouvrir" = "découvrir"
    "Decouvrir" = "Découvrir"
    "decouvrez" = "découvrez"
    "Decouvrez" = "Découvrez"
    "decouvert" = "découvert"
    "detail" = "détail"
    "Detail" = "Détail"
    "details" = "détails"
    "Details" = "Détails"
    "detaille" = "détaillé"
    "detaillee" = "détaillée"
    "determiner" = "déterminer"
    "determine" = "détermine"
    "depense" = "dépense"
    "Depense" = "Dépense"
    "depenses" = "dépenses"
    "Depenses" = "Dépenses"
    "deployer" = "déployer"
    "deploiement" = "déploiement"
    "demarche" = "démarche"
    "Demarche" = "Démarche"
    "demarches" = "démarches"
    "delegue" = "délégué"
    "Delegue" = "Délégué"
    "delai" = "délai"
    "Delai" = "Délai"
    "delais" = "délais"
    "fevrier" = "février"
    "Fevrier" = "Février"
    "fecondation" = "fécondation"
    "fertilite" = "fertilité"
    "Fertilite" = "Fertilité"
    "meteo" = "météo"
    "Meteo" = "Météo"
    "meteorologique" = "météorologique"
    "ble" = "blé"
    "Ble" = "Blé"
    "mais" = "maïs"  # Attention: "mais" conjonction existe aussi
    "Mais" = "Maïs"  # Attention contextuel
    "cafe" = "café"
    "Cafe" = "Café"
    "cacao" = "cacao"  # Correct sans accent
    "hevea" = "hévéa"
    "Hevea" = "Hévéa"
    "manioc" = "manioc"  # Correct
    "igname" = "igname"  # Correct
    "arachide" = "arachide"  # Correct
    "plantain" = "plantain"  # Correct
    "palmier" = "palmier"  # Correct
    "avocat" = "avocat"  # Correct
    "mangue" = "mangue"  # Correct
    "papaye" = "papaye"  # Correct
    "agrume" = "agrume"  # Correct
    "ananas" = "ananas"  # Correct
    "tomate" = "tomate"  # Correct
    "oignon" = "oignon"  # Correct
    "carotte" = "carotte"  # Correct
    "concombre" = "concombre"  # Correct
    "aubergine" = "aubergine"  # Correct
    "piment" = "piment"  # Correct
    "poivron" = "poivron"  # Correct
    "chou" = "chou"  # Correct
    "laitue" = "laitue"  # Correct
    "gombo" = "gombo"  # Correct
    "pasteque" = "pastèque"
    "Pasteque" = "Pastèque"
    "sorgho" = "sorgho"  # Correct
    "coton" = "coton"  # Correct
    "tilapia" = "tilapia"  # Correct
    "clarias" = "clarias"  # Correct
    "poulet" = "poulet"  # Correct
    "pondeuse" = "pondeuse"  # Correct
    "bovin" = "bovin"  # Correct
    "caprin" = "caprin"  # Correct
    "porcin" = "porcin"  # Correct
    "lapin" = "lapin"  # Correct
    
    # Accents graves (è)
    "critere" = "critère"
    "Critere" = "Critère"
    "criteres" = "critères"
    "modele" = "modèle"
    "Modele" = "Modèle"
    "modeles" = "modèles"
    "probleme" = "problème"
    "Probleme" = "Problème"
    "problemes" = "problèmes"
    "systeme" = "système"
    "Systeme" = "Système"
    "systemes" = "systèmes"
    "espece" = "espèce"
    "Espece" = "Espèce"
    "especes" = "espèces"
    "strategie" = "stratégie"
    "Strategie" = "Stratégie"
    "strategies" = "stratégies"
    "categorie" = "catégorie"
    "Categorie" = "Catégorie"
    "categories" = "catégories"
    "propriete" = "propriété"
    "Propriete" = "Propriété"
    "societe" = "société"
    "Societe" = "Société"
    "variete" = "variété"
    "Variete" = "Variété"
    "varietes" = "variétés"
    "Varietes" = "Variétés"
    "qualite" = "qualité"
    "Qualite" = "Qualité"
    "quantite" = "quantité"
    "Quantite" = "Quantité"
    "securite" = "sécurité"
    "activite" = "activité"
    "Activite" = "Activité"
    "activites" = "activités"
    "productivite" = "productivité"
    "Productivite" = "Productivité"
    "rentabilite" = "rentabilité"
    "Rentabilite" = "Rentabilité"
    "possibilite" = "possibilité"
    "Possibilite" = "Possibilité"
    "capacite" = "capacité"
    "Capacite" = "Capacité"
    "communaute" = "communauté"
    "Communaute" = "Communauté"
    "opportunite" = "opportunité"
    "Opportunite" = "Opportunité"
    "opportunites" = "opportunités"
    "realite" = "réalité"
    "Realite" = "Réalité"
    "priorite" = "priorité"
    "Priorite" = "Priorité"
    "priorites" = "priorités"
    "diversite" = "diversité"
    "Diversite" = "Diversité"
    "duree" = "durée"
    "Duree" = "Durée"
    "entree" = "entrée"
    "Entree" = "Entrée"
    "entrees" = "entrées"
    "idee" = "idée"
    "Idee" = "Idée"
    "idees" = "idées"
    "annee" = "année"
    "Annee" = "Année"
    "annees" = "années"
    "journee" = "journée"
    "Journee" = "Journée"
    "journees" = "journées"
    "matinee" = "matinée"
    "Matinee" = "Matinée"
    "soiree" = "soirée"
    "Soiree" = "Soirée"
    "donnee" = "donnée"
    "Donnee" = "Donnée"
    "donnees" = "données"
    "Donnees" = "Données"
    "creee" = "créée"
    "cree" = "créé"
    "crees" = "créés"
    "cle" = "clé"
    "Cle" = "Clé"
    "cles" = "clés"
    "ble" = "blé"
    
    # Accents circonflexes (ê, î, ô, û, â)
    "foret" = "forêt"
    "Foret" = "Forêt"
    "forets" = "forêts"
    "fenetre" = "fenêtre"
    "Fenetre" = "Fenêtre"
    "enquete" = "enquête"
    "Enquete" = "Enquête"
    "fete" = "fête"
    "Fete" = "Fête"
    "tete" = "tête"
    "Tete" = "Tête"
    "pret" = "prêt"
    "Pret" = "Prêt"
    "prets" = "prêts"
    "prete" = "prête"
    "arret" = "arrêt"
    "Arret" = "Arrêt"
    "interet" = "intérêt"
    "Interet" = "Intérêt"
    "interets" = "intérêts"
    "controle" = "contrôle"
    "Controle" = "Contrôle"
    "controler" = "contrôler"
    "role" = "rôle"
    "Role" = "Rôle"
    "roles" = "rôles"
    "cote" = "côté"
    "Cote" = "Côté"
    "cotes" = "côtés"
    "tot" = "tôt"
    "plutot" = "plutôt"
    "Plutot" = "Plutôt"
    "depot" = "dépôt"
    "Depot" = "Dépôt"
    "depots" = "dépôts"
    "hopital" = "hôpital"
    "Hopital" = "Hôpital"
    "hotel" = "hôtel"
    "Hotel" = "Hôtel"
    "ile" = "île"
    "Ile" = "Île"
    "iles" = "îles"
    "chaine" = "chaîne"
    "Chaine" = "Chaîne"
    "maitre" = "maître"
    "Maitre" = "Maître"
    "maitrise" = "maîtrise"
    "Maitrise" = "Maîtrise"
    "connaitre" = "connaître"
    "Connaitre" = "Connaître"
    "paraitre" = "paraître"
    "apparaitre" = "apparaître"
    "naitre" = "naître"
    "croitre" = "croître"
    "accroitre" = "accroître"
    "cout" = "coût"
    "Cout" = "Coût"
    "couts" = "coûts"
    "aout" = "août"
    "Aout" = "Août"
    "gout" = "goût"
    "Gout" = "Goût"
    "sure" = "sûre"
    "surs" = "sûrs"
    "sur " = "sûr "  # Attention contextuel
    "mur " = "mûr "  # Attention contextuel
    "mure" = "mûre"
    "murs" = "mûrs"
    "bruler" = "brûler"
    "brule" = "brûlé"
    "age" = "âge"
    "Age" = "Âge"
    "ages" = "âgés"
    "ame" = "âme"
    "Ame" = "Âme"
    "ane" = "âne"
    "tache" = "tâche"
    "Tache" = "Tâche"
    "taches" = "tâches"
    "Taches" = "Tâches"
    "grace" = "grâce"
    "Grace" = "Grâce"
    
    # Cédille (ç)
    "francais" = "français"
    "Francais" = "Français"
    "francaise" = "française"
    "Francaise" = "Française"
    "francaises" = "françaises"
    "facon" = "façon"
    "Facon" = "Façon"
    "facons" = "façons"
    "lecon" = "leçon"
    "Lecon" = "Leçon"
    "lecons" = "leçons"
    "garcon" = "garçon"
    "Garcon" = "Garçon"
    "garcons" = "garçons"
    "recoit" = "reçoit"
    "Recoit" = "Reçoit"
    "recu" = "reçu"
    "Recu" = "Reçu"
    "recue" = "reçue"
    "recus" = "reçus"
    "apercu" = "aperçu"
    "Apercu" = "Aperçu"
    "decu" = "déçu"
    "Decu" = "Déçu"
    "decue" = "déçue"
    "concu" = "conçu"
    "Concu" = "Conçu"
    "concue" = "conçue"
    "commencer" = "commencer"  # Attention: bien écrit
    "commenca" = "commença"
    "avanca" = "avança"
    "lanca" = "lança"
    "placa" = "plaça"
    "remerca" = "remerça"  # Rare
    "effaca" = "effaça"
    
    # Mots techniques agricoles
    "engrais" = "engrais"  # Correct
    "semis" = "semis"  # Correct
    "repiquer" = "repiquer"  # Correct
    "repiquage" = "repiquage"  # Correct
    "sarclage" = "sarclage"  # Correct
    "buttage" = "buttage"  # Correct
    "desherbage" = "désherbage"
    "Desherbage" = "Désherbage"
    "fertilisant" = "fertilisant"  # Correct
    "pesticide" = "pesticide"  # Correct
    "herbicide" = "herbicide"  # Correct
    "fongicide" = "fongicide"  # Correct
    "insecticide" = "insecticide"  # Correct
    "irrigation" = "irrigation"  # Correct
    "drainage" = "drainage"  # Correct
    "compost" = "compost"  # Correct
    "fumier" = "fumier"  # Correct
    "amendement" = "amendement"  # Correct
    "pheromone" = "phéromone"
    "Pheromone" = "Phéromone"
    "phytosanitaire" = "phytosanitaire"  # Correct
    "mecanisation" = "mécanisation"
    "Mecanisation" = "Mécanisation"
    "mecanise" = "mécanisé"
    "seche" = "sèche"
    "Seche" = "Sèche"
    "secheresse" = "sécheresse"
    "Secheresse" = "Sécheresse"
    "precoce" = "précoce"
    "Precoce" = "Précoce"
    "heteroside" = "hétéroside"
    
    # Termes web/UI
    "cree" = "créé"
    "creez" = "créez"
    "Creez" = "Créez"
    "creer" = "créer"
    "Creer" = "Créer"
    "gerez" = "gérez"
    "Gerez" = "Gérez"
    "gerer" = "gérer"
    "Gerer" = "Gérer"
    "geree" = "gérée"
    "generer" = "générer"
    "Generer" = "Générer"
    "genere" = "généré"
    "generee" = "générée"
    "selectionnez" = "sélectionnez"
    "Selectionnez" = "Sélectionnez"
    "selectionner" = "sélectionner"
    "Selectionner" = "Sélectionner"
    "selectionne" = "sélectionné"
    "selectionnee" = "sélectionnée"
    "acceder" = "accéder"
    "Acceder" = "Accéder"
    "accedez" = "accédez"
    "Accedez" = "Accédez"
    "verifier" = "vérifier"
    "Verifier" = "Vérifier"
    "verifiez" = "vérifiez"
    "verifie" = "vérifié"
    "completez" = "complétez"
    "Completez" = "Complétez"
    "completer" = "compléter"
    "Completer" = "Compléter"
    "complete" = "complété"
    "integrer" = "intégrer"
    "Integrer" = "Intégrer"
    "integre" = "intégré"
    "integree" = "intégrée"
    "executez" = "exécutez"
    "Executez" = "Exécutez"
    "executer" = "exécuter"
    "Executer" = "Exécuter"
    "execute" = "exécuté"
    "executee" = "exécutée"
    "parametres" = "paramètres"
    "Parametres" = "Paramètres"
    "parametre" = "paramètre"
    "Parametre" = "Paramètre"
    "numero" = "numéro"
    "Numero" = "Numéro"
    "numeros" = "numéros"
    
    # Autres mots courants
    "durable" = "durable"  # Correct
    "agricole" = "agricole"  # Correct
    "technique" = "technique"  # Correct
    "pratique" = "pratique"  # Correct
    "economique" = "économique"
    "ecologique" = "écologique"
    "Ecologique" = "Écologique"
    "biologique" = "biologique"  # Correct
    "climatique" = "climatique"  # Correct
    "geographique" = "géographique"
    "Geographique" = "Géographique"
    "meteorologique" = "météorologique"
    "Meteorologique" = "Météorologique"
    "supplementaire" = "supplémentaire"
    "Supplementaire" = "Supplémentaire"
    "supplementaires" = "supplémentaires"
    "elementaire" = "élémentaire"
    "Elementaire" = "Élémentaire"
    "immediat" = "immédiat"
    "Immediat" = "Immédiat"
    "immediate" = "immédiate"
    "eventuellement" = "éventuellement"
    "Eventuellement" = "Éventuellement"
    "egalement" = "également"
    "Egalement" = "Également"
    "generalement" = "généralement"
    "Generalement" = "Généralement"
    "reellement" = "réellement"
    "Reellement" = "Réellement"
    "regulierement" = "régulièrement"
    "Regulierement" = "Régulièrement"
    "completement" = "complètement"
    "Completement" = "Complètement"
    "entierement" = "entièrement"
    "Entierement" = "Entièrement"
    "particulierement" = "particulièrement"
    "Particulierement" = "Particulièrement"
    "premiérement" = "premièrement"
    "Premiérement" = "Premièrement"
    "deuxièmement" = "deuxièmement"  # Correct
    "frequemment" = "fréquemment"
    "Frequemment" = "Fréquemment"
    "evenement" = "événement"
    "Evenement" = "Événement"
    "evenements" = "événements"
    "element" = "élément"
    "Element" = "Élément"
    "elements" = "éléments"
    "Elements" = "Éléments"
    "etablir" = "établir"
    "Etablir" = "Établir"
    "etabli" = "établi"
    "etablie" = "établie"
    "etablissement" = "établissement"
    "Etablissement" = "Établissement"
    
    # Légales / CGU
    "responsabilite" = "responsabilité"
    "Responsabilite" = "Responsabilité"
    "confidentialite" = "confidentialité"
    "Confidentialite" = "Confidentialité"
    "propriete" = "propriété"
    "Propriete" = "Propriété"
    "legalite" = "légalité"
    "Legalite" = "Légalité"
    "legales" = "légales"
    "Legales" = "Légales"
    "legal" = "légal"
    "Legal" = "Légal"
    "reserve" = "réservé"
    "Reserve" = "Réservé"
    "reservee" = "réservée"
    "reservees" = "réservées"
    "reserves" = "réservés"
    "protege" = "protégé"
    "Protege" = "Protégé"
    "protegee" = "protégée"
    "proteger" = "protéger"
    "Proteger" = "Protéger"
    "modifie" = "modifié"
    "Modifie" = "Modifié"
    "modifiee" = "modifiée"
    "modifier" = "modifier"  # Correct
    "limite" = "limité"
    "Limite" = "Limité"
    "limitee" = "limitée"
    "limiter" = "limiter"  # Correct
    "autorise" = "autorisé"
    "Autorise" = "Autorisé"
    "autorisee" = "autorisée"
    "autoriser" = "autoriser"  # Correct
    "interdit" = "interdit"  # Correct
    "interdite" = "interdite"  # Correct
}

# Compteur
$totalReplacements = 0
$filesModified = 0

# Parcourir tous les fichiers .tsx dans app/
$files = Get-ChildItem -Path "$projectPath\app" -Recurse -Filter "*.tsx"

foreach ($file in $files) {
    Write-Host "`nTraitement: $($file.FullName)" -ForegroundColor Cyan
    
    # Lire le contenu
    $content = [System.IO.File]::ReadAllText($file.FullName, [System.Text.Encoding]::UTF8)
    $originalContent = $content
    $fileReplacements = 0
    
    # Appliquer les remplacements
    foreach ($key in $replacements.Keys) {
        $value = $replacements[$key]
        if ($content -match [regex]::Escape($key)) {
            $count = ([regex]::Matches($content, [regex]::Escape($key))).Count
            $content = $content -replace [regex]::Escape($key), $value
            $fileReplacements += $count
            Write-Host "  - '$key' -> '$value' ($count)" -ForegroundColor Green
        }
    }
    
    # Sauvegarder si modifié
    if ($content -ne $originalContent) {
        [System.IO.File]::WriteAllText($file.FullName, $content, [System.Text.Encoding]::UTF8)
        $totalReplacements += $fileReplacements
        $filesModified++
        Write-Host "  => $fileReplacements remplacements" -ForegroundColor Yellow
    } else {
        Write-Host "  => Aucun changement" -ForegroundColor Gray
    }
}

Write-Host "`n========================================" -ForegroundColor Magenta
Write-Host "TERMINÉ" -ForegroundColor Magenta
Write-Host "Fichiers modifiés: $filesModified" -ForegroundColor White
Write-Host "Total remplacements: $totalReplacements" -ForegroundColor White
Write-Host "========================================" -ForegroundColor Magenta
