# ==============================================
# KESSEL-WEB : Correction orthographique (accents)
# Executer depuis C:\Users\user\Desktop\kessel-web\
# ==============================================

$projectPath = "C:\Users\user\Desktop\kessel-web"

# Liste des remplacements (sans accent -> avec accent)
# Format: "mot_sans_accent|mot_avec_accent"
$replacementsList = @(
    # Mots avec e accent aigu
    "etape|étape"
    "Etape|Étape"
    "equipe|équipe"
    "Equipe|Équipe"
    "ecran|écran"
    "Ecran|Écran"
    "energie|énergie"
    "Energie|Énergie"
    "etat|état"
    "Etat|État"
    "etude|étude"
    "Etude|Étude"
    "elevage|élevage"
    "Elevage|Élevage"
    "etre|être"
    "Etre|Être"
    "etes|êtes"
    "Etes|Êtes"
    "evenement|événement"
    "Evenement|Événement"
    "evenements|événements"
    "element|élément"
    "Element|Élément"
    "elements|éléments"
    "Elements|Éléments"
    "etablir|établir"
    "etabli|établi"
    "etablissement|établissement"
    "recolte|récolte"
    "Recolte|Récolte"
    "cereale|céréale"
    "cereales|céréales"
    "legume|légume"
    "legumes|légumes"
    "securite|sécurité"
    "Securite|Sécurité"
    "generale|générale"
    "generales|générales"
    "genere|génère"
    "generer|générer"
    "Generer|Générer"
    "generalement|généralement"
    "methode|méthode"
    "Methode|Méthode"
    "periode|période"
    "Periode|Période"
    "telecharger|télécharger"
    "Telecharger|Télécharger"
    "telechargez|téléchargez"
    "Telechargez|Téléchargez"
    "telephone|téléphone"
    "Telephone|Téléphone"
    "presente|présente"
    "preference|préférence"
    "different|différent"
    "differente|différente"
    "differents|différents"
    "interessant|intéressant"
    "interesse|intéressé"
    "necessaire|nécessaire"
    "necessaires|nécessaires"
    "developpement|développement"
    "Developpement|Développement"
    "developpe|développé"
    "repondre|répondre"
    "repond|répond"
    "reponse|réponse"
    "Reponse|Réponse"
    "reseau|réseau"
    "Reseau|Réseau"
    "resume|résumé"
    "resultat|résultat"
    "Resultat|Résultat"
    "resultats|résultats"
    "reference|référence"
    "references|références"
    "region|région"
    "Region|Région"
    "regions|régions"
    "Regions|Régions"
    "regulier|régulier"
    "reguliere|régulière"
    "regulierement|régulièrement"
    "repartition|répartition"
    "benefice|bénéfice"
    "benefices|bénéfices"
    "beneficiaire|bénéficiaire"
    "Beneficiaire|Bénéficiaire"
    "beneficiaires|bénéficiaires"
    "specifique|spécifique"
    "specifiques|spécifiques"
    "speculation|spéculation"
    "Speculation|Spéculation"
    "speculations|spéculations"
    "Speculations|Spéculations"
    "prevision|prévision"
    "previsions|prévisions"
    "prevu|prévu"
    "prevue|prévue"
    "prevoir|prévoir"
    "precis|précis"
    "precise|précise"
    "precision|précision"
    "preparation|préparation"
    "Preparation|Préparation"
    "preparer|préparer"
    "prepare|préparé"
    "premiere|première"
    "Premiere|Première"
    "premieres|premières"
    "prefere|préfère"
    "recommande|recommandé"
    "recommandee|recommandée"
    "demarrer|démarrer"
    "demarre|démarré"
    "demarrage|démarrage"
    "debuter|débuter"
    "debut|début"
    "Debut|Début"
    "decembre|décembre"
    "Decembre|Décembre"
    "decision|décision"
    "Decision|Décision"
    "decouvrir|découvrir"
    "Decouvrir|Découvrir"
    "decouvrez|découvrez"
    "Decouvrez|Découvrez"
    "detail|détail"
    "Detail|Détail"
    "details|détails"
    "Details|Détails"
    "detaille|détaillé"
    "detaillee|détaillée"
    "determiner|déterminer"
    "determine|déterminé"
    "depense|dépense"
    "Depense|Dépense"
    "depenses|dépenses"
    "Depenses|Dépenses"
    "deployer|déployer"
    "deploiement|déploiement"
    "demarche|démarche"
    "demarches|démarches"
    "delegue|délégué"
    "delai|délai"
    "delais|délais"
    "fevrier|février"
    "Fevrier|Février"
    "fertilite|fertilité"
    "meteo|météo"
    "Meteo|Météo"
    "meteorologique|météorologique"
    "cafe|café"
    "Cafe|Café"
    "hevea|hévéa"
    "Hevea|Hévéa"
    "pasteque|pastèque"
    "Pasteque|Pastèque"
    "desherbage|désherbage"
    "mecanisation|mécanisation"
    "mecanise|mécanisé"
    "seche|sèche"
    "secheresse|sécheresse"
    "Secheresse|Sécheresse"
    "precoce|précoce"
    "creez|créez"
    "Creez|Créez"
    "creer|créer"
    "Creer|Créer"
    "cree|créé"
    "creee|créée"
    "gerez|gérez"
    "Gerez|Gérez"
    "gerer|gérer"
    "Gerer|Gérer"
    "geree|gérée"
    "selectionnez|sélectionnez"
    "Selectionnez|Sélectionnez"
    "selectionner|sélectionner"
    "selectionne|sélectionné"
    "acceder|accéder"
    "Acceder|Accéder"
    "accedez|accédez"
    "verifier|vérifier"
    "Verifier|Vérifier"
    "verifiez|vérifiez"
    "verifie|vérifié"
    "completez|complétez"
    "completer|compléter"
    "complete|complété"
    "integrer|intégrer"
    "integre|intégré"
    "integree|intégrée"
    "executez|exécutez"
    "executer|exécuter"
    "execute|exécuté"
    "parametres|paramètres"
    "Parametres|Paramètres"
    "parametre|paramètre"
    "numero|numéro"
    "Numero|Numéro"
    "numeros|numéros"
    "economique|économique"
    "Economique|Économique"
    "ecologique|écologique"
    "Ecologique|Écologique"
    "geographique|géographique"
    "supplementaire|supplémentaire"
    "supplementaires|supplémentaires"
    "elementaire|élémentaire"
    "immediat|immédiat"
    "immediate|immédiate"
    "eventuellement|éventuellement"
    "egalement|également"
    "Egalement|Également"
    "reellement|réellement"
    "completement|complètement"
    "entierement|entièrement"
    "particulierement|particulièrement"
    "frequemment|fréquemment"
    
    # Mots avec e accent grave
    "critere|critère"
    "criteres|critères"
    "modele|modèle"
    "Modele|Modèle"
    "modeles|modèles"
    "probleme|problème"
    "Probleme|Problème"
    "problemes|problèmes"
    "systeme|système"
    "Systeme|Système"
    "systemes|systèmes"
    "espece|espèce"
    "especes|espèces"
    "strategie|stratégie"
    "Strategie|Stratégie"
    "strategies|stratégies"
    "categorie|catégorie"
    "Categorie|Catégorie"
    "categories|catégories"
    "propriete|propriété"
    "Propriete|Propriété"
    "societe|société"
    "Societe|Société"
    "variete|variété"
    "Variete|Variété"
    "varietes|variétés"
    "qualite|qualité"
    "Qualite|Qualité"
    "quantite|quantité"
    "Quantite|Quantité"
    "activite|activité"
    "Activite|Activité"
    "activites|activités"
    "productivite|productivité"
    "rentabilite|rentabilité"
    "possibilite|possibilité"
    "capacite|capacité"
    "communaute|communauté"
    "opportunite|opportunité"
    "opportunites|opportunités"
    "realite|réalité"
    "priorite|priorité"
    "priorites|priorités"
    "diversite|diversité"
    "duree|durée"
    "Duree|Durée"
    "entree|entrée"
    "entrees|entrées"
    "idee|idée"
    "idees|idées"
    "annee|année"
    "Annee|Année"
    "annees|années"
    "journee|journée"
    "donnee|donnée"
    "Donnee|Donnée"
    "donnees|données"
    "Donnees|Données"
    "cle|clé"
    "Cle|Clé"
    "cles|clés"
    
    # Mots avec accent circonflexe
    "foret|forêt"
    "Foret|Forêt"
    "forets|forêts"
    "fenetre|fenêtre"
    "enquete|enquête"
    "fete|fête"
    "tete|tête"
    "pret|prêt"
    "prets|prêts"
    "prete|prête"
    "arret|arrêt"
    "interet|intérêt"
    "Interet|Intérêt"
    "interets|intérêts"
    "controle|contrôle"
    "Controle|Contrôle"
    "controler|contrôler"
    "role|rôle"
    "Role|Rôle"
    "roles|rôles"
    "cote|côté"
    "cotes|côtés"
    "plutot|plutôt"
    "depot|dépôt"
    "Depot|Dépôt"
    "depots|dépôts"
    "hopital|hôpital"
    "hotel|hôtel"
    "ile|île"
    "iles|îles"
    "chaine|chaîne"
    "Chaine|Chaîne"
    "maitre|maître"
    "maitrise|maîtrise"
    "connaitre|connaître"
    "paraitre|paraître"
    "apparaitre|apparaître"
    "cout|coût"
    "Cout|Coût"
    "couts|coûts"
    "aout|août"
    "Aout|Août"
    "gout|goût"
    "bruler|brûler"
    "brule|brûlé"
    "tache|tâche"
    "Tache|Tâche"
    "taches|tâches"
    "grace|grâce"
    "Grace|Grâce"
    
    # Mots avec cedille
    "francais|français"
    "Francais|Français"
    "francaise|française"
    "Francaise|Française"
    "francaises|françaises"
    "facon|façon"
    "Facon|Façon"
    "facons|façons"
    "lecon|leçon"
    "lecons|leçons"
    "garcon|garçon"
    "garcons|garçons"
    "recoit|reçoit"
    "recu|reçu"
    "Recu|Reçu"
    "recue|reçue"
    "recus|reçus"
    "apercu|aperçu"
    "Apercu|Aperçu"
    "decu|déçu"
    "decue|déçue"
    "concu|conçu"
    "concue|conçue"
    
    # Mots courants
    "deja|déjà"
    "Deja|Déjà"
    "voila|voilà"
    "a propos|à propos"
    "A propos|À propos"
    
    # Termes legaux
    "responsabilite|responsabilité"
    "confidentialite|confidentialité"
    "Confidentialite|Confidentialité"
    "legalite|légalité"
    "legales|légales"
    "Legales|Légales"
    "legal|légal"
    "Legal|Légal"
    "reserve|réservé"
    "reservee|réservée"
    "protege|protégé"
    "protegee|protégée"
    "proteger|protéger"
    "modifie|modifié"
    "modifiee|modifiée"
    "limite|limité"
    "limitee|limitée"
    "autorise|autorisé"
    "autorisee|autorisée"
)

# Compteur
$totalReplacements = 0
$filesModified = 0

# Parcourir tous les fichiers .tsx dans app/
$files = Get-ChildItem -Path "$projectPath\app" -Recurse -Filter "*.tsx"

foreach ($file in $files) {
    Write-Host "`nTraitement: $($file.Name)" -ForegroundColor Cyan
    
    # Lire le contenu
    $content = [System.IO.File]::ReadAllText($file.FullName, [System.Text.Encoding]::UTF8)
    $originalContent = $content
    $fileReplacements = 0
    
    # Appliquer les remplacements
    foreach ($pair in $replacementsList) {
        $parts = $pair -split '\|'
        $search = $parts[0]
        $replace = $parts[1]
        
        if ($content -cmatch $search) {
            $count = ([regex]::Matches($content, $search, [System.Text.RegularExpressions.RegexOptions]::None)).Count
            $content = $content -creplace $search, $replace
            $fileReplacements += $count
            Write-Host "  $search -> $replace ($count)" -ForegroundColor Green
        }
    }
    
    # Sauvegarder si modifie
    if ($content -ne $originalContent) {
        [System.IO.File]::WriteAllText($file.FullName, $content, [System.Text.Encoding]::UTF8)
        $totalReplacements += $fileReplacements
        $filesModified++
        Write-Host "  => $fileReplacements remplacements" -ForegroundColor Yellow
    } else {
        Write-Host "  => Aucun changement" -ForegroundColor Gray
    }
}

Write-Host "`n========================================" -ForegroundColor Magenta
Write-Host "TERMINE" -ForegroundColor Magenta
Write-Host "Fichiers modifies: $filesModified" -ForegroundColor White
Write-Host "Total remplacements: $totalReplacements" -ForegroundColor White
Write-Host "========================================" -ForegroundColor Magenta
